Team-Hanbae/Hanbae-Flutter

- lib/presentation/home/home_screen.dart
- lib/system/main.dart
Presentation 레이어의 화면 구조를 간단하게 미리 생성해놓습니다.
- 폴더구조
```bash
lib/
├── presentation/
│   ├── home/
│   ├── metronome/
│   ├── viewmodel/
```
- 폴더 구조 유지 위해서 기초적인 파일 생성
- main과 HomeScreen 연결
> [Feat] #3 기본 화면 구조 생성

- pubspec.yaml
BLoC 관련 패키지들을 추가합니다
- 이벤트 기반 상태관리: 기존 iOS에서 Combine을 사용중이라 유사할거라는 기대감
- 자료가 많아 보임: 검색시 결과 퀄리티가 높았음
```bash
flutter pub add flutter_bloc
```
```bash
flutter pub add freezed_annotation
flutter pub add --dev freezed build_runner
```
```bash
flutter pub add equatable
```
> [Chore] #5 Bloc, freezed, equatable 설치

- devtools_options.yaml
- lib/presentation/home/custom_jangdan_list_screen.dart
커스텀장단리스트스크린 앱바를 만들다가 말았어요,,
AppBar title, action버튼 만듦
> [Feat] #10 CustonJangdanListScreen 앱 바

- lib/theme/colors.dart
> [Feat] #15 컬러 등록

- lib/theme/colors.dart
> [Feat] #17 컬러 파일 수정

- lib/main.dart
- lib/presentation/home/home_screen.dart
- lib/theme/colors.dart
> [Feat] #19 홈 스크린 컬러 넣기

- lib/bloc/metronome/metronome_bloc.dart
- lib/bloc/metronome/metronome_event.dart
- lib/bloc/metronome/metronome_state.dart
- lib/main.dart
- lib/model/jangdan.dart
- lib/presentation/metronome/hanbae_board.dart
- lib/presentation/metronome/metronome_screen.dart
Bloc 사용 연습 겸 데이터 연동처리 해봤습니다.
- MetronomeBloc 구현
- MetronomeState 구현
- MetronomeEvent 구현
- Bloc 주입 (main.dart)
- Bakbar가 Accent의 Index를 참조하도록 변경
- 대응하는 Accent와 연동되려면 Index를 알고 있어야 하기 때문
- Bakbar 탭 제스처로 Accent가 변경되도록 구현
- ToggleAccent 이벤트 추가
- 색상 반영
> [Feat] #9 MetronomeBloc 간단구현

- lib/main.dart
- lib/presentation/metronome/metronome_control.dart
플마버튼이랑 BPM 숫자 있는 부분 row 높이가 크게 잡히는데 왜 그런지 모르겠어서 해결몬함!😎
> [Feat] #37 BPM controler UI 디자인 적용

- lib/bloc/metronome/metronome_bloc.dart
- lib/bloc/metronome/metronome_event.dart
- lib/presentation/metronome/hanbae_board.dart
- lib/presentation/metronome/metronome_screen.dart
- lib/presentation/metronome/metronome_setting_control.dart
- jangdanType에 따라서 SobakSegment가 표시됨
- Bakbar에 구분선 추가
- BakNumber 표기되도록 변경
> [Feat] #31 소박보기 구현

- lib/bloc/metronome/metronome_bloc.dart
- lib/presentation/metronome/metronome_control.dart
- lib/presentation/metronome/metronome_screen.dart
clamp로 제한돼 있었던거 10, 300으로 수정
jangdan 변수 만들고 넘겨주기
plus, minus 버튼 동작하게 하기, 그에 따라서 BPM text 갱신
> [Feat] #30 BPM 변경 기능

- lib/presentation/home/home_screen.dart
- lib/theme/text_styles.dart
> [Feat] #44 홈화면에서 내가 저장한 장단 영역 삭제

- lib/bloc/metronome/metronome_bloc.dart
- lib/bloc/metronome/metronome_event.dart
- lib/bloc/metronome/metronome_state.dart
- lib/presentation/metronome/metronome_control.dart
빠르기찾기 기능을 구현합니다.
- TapTempo 이벤트 추가, 구현
- StopTapping 이벤트 추가, 구현
- 마지막 Tap에서 6초 지나면 종료되도록 설정
- 다른 이벤트 발생시 StopTapping 이벤트 호출하도록 설정
- isTapping 상태 추가
- isTapping에 따라 UI 반영
- 빠르기 문자열 -> 계속 탭해주세요
- BPM 숫자 -> 컬러링
- 빠르기 찾기 버튼 -> 탭 버튼
- play 시작시 시작버튼 -> 멈춤버튼으로 바뀌도록 수정
> [Feat] #32 빠르기 찾기

- lib/bloc/metronome/metronome_bloc.dart
BPM 기준을 대박 기준으로 변경합니다
60BPM = 1분에 대박 60회
- 표기되는 BPM에 대박당 평균 소박 갯수를 곱해 interval을 계산함
- 대박마다 소박 갯수가 다른 경우가 있기 때문에 평균을 냄
- BPM 변경시 마지막 재생 시점에서 다음 재생되어야 할 시점까지의 시간을 계산
> [Feat] #50 BPM 연산 로직 변경

- android/app/src/main/res/values/styles.xml
- lib/presentation/metronome/metronome_screen.dart
- pubspec.yaml
> [Feat] #57 로딩화면

- android/app/src/main/AndroidManifest.xml
- lib/presentation/home/home_screen.dart
- pubspec.yaml
설문 배너에 링크를 답니다
- url_launcher
- Android 설정
- 권한 설정
- 쿼리 설정
- ontap 제스처
- 링크로 연결
> [Feat] #62 설문 배너 링크

- lib/presentation/metronome/metronome_control.dart
LongTap 제스처로 BPM을 변경합니다
- 10단위로 변경되도록 구현
- 1의자리는 0으로 맞추기 위한 로직
- 롱탭이 지속되는 동안 타이머 실행시켜서 이벤트 호출
> [Feat] #60 BPM 변경 LongTap

- .gitignore
- android/app/build.gradle.kts
- android/app/src/main/kotlin/com/example/hanbae/MainActivity.kt
- pubspec.yaml
> [feat] #68 key 추가, 안드로이드 빌드 세팅

- pubspec.yaml
> [Release] #68 빌드 번호 업데이트

- lib/presentation/metronome/hanbae_board.dart
- lib/presentation/metronome/metronome_control.dart
- lib/presentation/metronome/metronome_options.dart
- lib/presentation/metronome/metronome_screen.dart
- lib/theme/text_styles.dart
- 상하패딩값 수정
- 색상수정
- 버튼 사이즈, 텍스트 사이즈, 패딩값 수정
> [Feat] #72 메트로놈스크린 UI 사이즈 수정

- android/app/build.gradle.kts
- pubspec.yaml
플레이스토어에 올라간 앱에서 사운드가 재생되지 않는 이슈
- isShrinkResources = true  -> false
- 앱에서 사용하지 않는 리소스를 자동으로 최적화해주는 기능
- 아마 사운드 에셋을 감지 못해서 사용 안한다고 판단하고 지워버리는듯
- 옵션 off
> [Fix] #82 사운드 안나는 이슈

- pubspec.yaml
버전 넘버링을 변경합니다.
- 생각해보니까 지금 베타테스트 주간이라 1.0.0 보다는 0.0.0 번대 넘버링이 맞는듯
> [Release] #107 ver 0.3.0

- lib/presentation/home/home_screen.dart
- pubspec.yaml
> [Release] #109 ver 1.0.0

- lib/utils/dialog.dart
> [Fix] #128 고산자 폰트 색상 누락 수정

- pubspec.yaml
> [Release] #146 ver 1.0.3
